[workspace]
members = [
  "crates/proto",
  "crates/client",
  "crates/client/test-wasm",
  "crates/worker",
  "crates/orchestrator",
  
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
serde = "1.0"
serde_json = "1.0"
base64 = "0.22.1"
uuid = { version = "1", features = ["serde", "v4"] }
anyhow = "1.0"
thiserror = "2.0"
futures-util = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12.23", features = ["json", "rustls-tls"]}
axum = { version = "0.8.4"}
tracing = "0.1"
tracing-subscriber = "0.3.20"
async-trait = "0.1.50"
sha2 = "0.10.9"
hex = "0.4.3"
clap = { version = "4", features = ["derive"] }
