[package]
name = "orchestrator"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["signal"]}
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
axum = { workspace = true }
mini-lambda-proto = { path = "../proto" }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
clap = { workspace = true }
tower-http = { version = "0.6.6", features = ["trace"] }
